#Welcome to the Ships 5+ config. The vessels default data has moved 
#into the folder labelled 'VesselTypes'.

#With this config you are able to change a lot including what
#supported plugins are enabled, the AutoPilot, default water level,
#etc.

#The plugin support is now in generation 2, this means you are able
#to change a few more features other then enabling the plugin support.

Structure:
  StructureLimits:
    #This is the limit to the checking tool for air. The higher this 
    #value is the taller your WaterBasedVessels can be, but at the 
    #cost of server power resources.
    airCheckGap: 120
    #This limits the size of all vessels, higher it goes, the more
    #server resources you needed
    trackLimit: 5000
  Signs:
    #This will force the owners name on the licence sign. It is
    #updated when the vessel moves.
    ForceUsernameOnLicenceSign: false
    EOT:
      #This is how quickly EOT vessels will move
      repeat: 130
      #enable EOT
      enabled: false
    AutoPilot:
      #This is the height that the vessels will fly at when autopilot is  
      #enabled. It does this to reduce the chance of hitting a mountain.
      height: 120
      #Repeat is the delay that the autopilot move command is activated.
      repeat: 130
      #Enable Autopilot
      enabled: false
    Cell:
      repeat: 130
      enabled: false
  
Inventory:
  #enabling this may cause a glitch where players can dupe there 
  #inventory's, but its a cool feature
  keepInventorysOpen: false

World:
  #If a water based vessel is leaving a water trail behind it, change 
  #this to match the default water level of your worlds (will be
  #changeable per world in a later update).
  defaultWaterLevel: 63
  #Protected Vessels allows users to protect their Ships. This may cause
  #Lag. 
  ProtectedVessels:
    #BlockBreak protects the vessel from being destroyed by players.
    BlockBreak: false
    #Stops others from snooping through a Ships inventory
    InventoryOpen: false
    #Stops vessels from burning to a crisp
    FireProtect2: false
    ExplodeProtect:
      #Stops Creepers from blowing up the Ships. 
      #this will still do damage to the players
      Creeper: false
      #Stops Creepers from blowing up the Ships.
      #this will still do damage to the players
      TNT: false
    EntityProtect:
      #Stops enderDragons from doing damage to vessels.
      Enderdragon: false
      #Stops Wither from doing damage to vessels.
      Wither: false
      #Stops enderman picking up/placing blocks on your vessels
      EnderMan: false
    VesselsFallOutSky:
      #enables the ability for vessels to fall out of the sky
      enabled: false

VesselLoading:
  #this feature will remove vessel files that are not loading correctly. 
  #This will save space, increase loading time, however there is no
  #chance of recovering the file 
  DeleteFailedLoads: false	

Messages:
  #enable if messages appear for users
  enabled: true
  #change the Ship is too small message. 
  #%currentSize% displays the size of the vessel
  #%minForVessel% displays the min amount of blocks needed for the vessel
  ShipTooSmall: 'The current size of your vessel is %currentSize%, Your vessel needs to be %minForVessel% or lower.'
  #change the Ship is too large message. 
  #%currentSize% displays the size of the vessel
  #%minForVessel% displays the min amount of blocks needed for the vessel
  ShipTooBig: 'The current size of your vessel is %currentSize%, Your vessel needs to be %maxForVessel% or higher.'  
  #change the Ship needs more fuel. 
  #%fuel% displays the fuel type needed, that maybe fuel or light
  OutOfFuel: 'Your vessel is out of %fuel%.'
  #change the Must be in air. 
  #%material% displays the material the vessel must be in.
  MustBeIn: 'Your vessel must be in %material%.'
  #change the Ship needs Burner. 
  #%material% displays the material needed
  Needs: 'Your vessel needs %material%.'
  #change the Ship is off by X amount of wool
  #%amount% displays the amount the player is off by
  #%material% displays the material(s) required by the vessel
  OffBy: 'Your vessel needs %amount% of %material%.'
  #change the found material in way. 
  #%material% displays the material that is in way
  FoundInWay: 'Found %material% in way.'

MCVersion: 1.8.8
